# Generated by Django 2.1 on 2021-01-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='Mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='Mobile1',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='OfficialEmail',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='PersonalEmail',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
