# Generated by Django 2.1 on 2021-01-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_auto_20210118_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='messagetemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Message Templates',
            },
        ),
    ]
