# Generated by Django 2.1 on 2021-01-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_messagetemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetemp',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='messagetemp',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='messagetemp',
            name='id',
        ),
        migrations.AddField(
            model_name='messagetemp',
            name='Template_id',
            field=models.CharField(default='123', max_length=50, primary_key=True, serialize=False),
        ),
    ]
