# Generated by Django 2.1 on 2021-01-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0004_auto_20210119_0108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='groupN',
        ),
    ]
