# Generated by Django 2.1 on 2021-01-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0005_delete_groupn'),
    ]

    operations = [
        migrations.CreateModel(
            name='broadcastmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageTemplate', models.CharField(max_length=500)),
                ('Group', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='message',
        ),
    ]
