# Generated by Django 2.1 on 2021-01-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0008_auto_20210119_0224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='delivery',
        ),
        migrations.AlterModelOptions(
            name='broadcastmessage',
            options={'verbose_name_plural': 'deliveries'},
        ),
    ]
