# Generated by Django 2.1 on 2021-01-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0010_auto_20210119_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastmessage',
            options={'verbose_name_plural': 'Broadcast Messages'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Deliveries'},
        ),
    ]
