# Generated by Django 2.1 on 2021-01-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0012_auto_20210120_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='group',
        ),
    ]
