# Generated by Django 2.1 on 2021-01-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0013_remove_records_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.group'),
        ),
    ]
