# Generated by Django 2.1 on 2021-01-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0014_records_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='Group',
        ),
        migrations.RemoveField(
            model_name='records',
            name='group',
        ),
        migrations.DeleteModel(
            name='group',
        ),
    ]
