# Generated by Django 2.1 on 2021-01-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0016_auto_20210121_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='Group',
        ),
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='MessageTemplate',
        ),
        migrations.DeleteModel(
            name='broadcastmessage',
        ),
        migrations.DeleteModel(
            name='messagetemp',
        ),
    ]
