# Generated by Django 2.1 on 2021-01-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0017_auto_20210121_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='broadcastmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=400)),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.group')),
            ],
            options={
                'verbose_name_plural': 'Broadcast Messages',
            },
        ),
    ]
