# Generated by Django 2.1 on 2021-01-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0018_broadcastmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcastmessage',
            old_name='Title',
            new_name='Subject',
        ),
    ]
