# Generated by Django 2.1 on 2021-01-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0019_auto_20210121_0520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='number_of_recipients',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='Sms_status',
            new_name='sms_status',
        ),
    ]
