# Generated by Django 2.1 on 2021-01-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0020_auto_20210121_0617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='delivery',
        ),
    ]
